package plasma

import (
	"github.com/spf13/cobra"
)

// PlasmaCmd is the root command for plasma-related operations
var PlasmaCmd = &cobra.Command{
	Use:   "plasma",
	Short: "Plasma fusion operations",
	Long: `Plasma fusion operations for feeless transactions.

Plasma is generated by fusing QSR tokens to a beneficiary address.
Fused QSR can be unfused after 10 momentums (~1 hour).

Available subcommands:
  list   - List fusion entries
  get    - Get plasma info for current address
  fuse   - Fuse QSR for beneficiary
  cancel - Cancel fusion by ID`,
}

func init() {
	// Subcommands will register themselves
}
